[project]
name = 'stacks-contracts-poc'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'
requirements = []
[contracts.simple-bookmarks]
path = 'contracts/simple-bookmarks.clar'
clarity_version = 4
epoch = 'latest'

[contracts.simple-counter]
path = 'contracts/simple-counter.clar'
clarity_version = 4
epoch = 'latest'

[contracts.simple-flag]
path = 'contracts/simple-flag.clar'
clarity_version = 4
epoch = 'latest'

[contracts.simple-gm]
path = 'contracts/simple-gm.clar'
clarity_version = 4
epoch = 'latest'

[contracts.simple-kudos]
path = 'contracts/simple-kudos.clar'
clarity_version = 4
epoch = 'latest'

[contracts.simple-leaderboard]
path = 'contracts/simple-leaderboard.clar'
clarity_version = 4
epoch = 'latest'

[contracts.simple-level-up]
path = 'contracts/simple-level-up.clar'
clarity_version = 4
epoch = 'latest'

[contracts.simple-message]
path = 'contracts/simple-message.clar'
clarity_version = 4
epoch = 'latest'

[contracts.simple-ping-pong]
path = 'contracts/simple-ping-pong.clar'
clarity_version = 4
epoch = 'latest'

[contracts.simple-points]
path = 'contracts/simple-points.clar'
clarity_version = 4
epoch = 'latest'

[contracts.simple-reactions]
path = 'contracts/simple-reactions.clar'
clarity_version = 4
epoch = 'latest'

[contracts.simple-status]
path = 'contracts/simple-status.clar'
clarity_version = 4
epoch = 'latest'

[contracts.simple-todo]
path = 'contracts/simple-todo.clar'
clarity_version = 4
epoch = 'latest'

[contracts.simple-token]
path = 'contracts/simple-token.clar'
clarity_version = 4
epoch = 'latest'

[contracts.simple-nft]
path = 'contracts/simple-nft.clar'
clarity_version = 4
epoch = 'latest'

[contracts.wizard-token]
path = 'contracts/wizard-token.clar'
clarity_version = 4
epoch = 'latest'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.lints]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
